// shape-and-page.check.ts — guards the two canvas regressions this session found,
// and the namespace contract the shape/font/brand engines will depend on.
//
// Node cannot load a .tsx, so every check reaches a .ts (repo lesson 2026-10-03:
// 22 of 50 checks were dead for exactly that reason). Assert-based, no
// framework — see ARCHITECTURE.md.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { parseCanvasSpec } from "./canvas-schema.ts";
import { sanitizeCanvasSpec } from "./canvas-sanitize.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CSS = readFileSync(resolve(__dirname, "../index.css"), "utf8");
const BODY = [{ type: "callout" as const, tone: "info" as const, body: "x" }];

// ---- 1. the two phantom radius tokens -------------------------------------
//
// A var() with no definition invalidates the whole declaration, so a consumer
// computes to the property's initial value — for border-radius that is 0px.
// These two were used 14 times in index.css and defined nowhere, so every
// canvas control, video frame and graph skeleton rendered perfectly square in
// production. Proven in Chrome before the fix: var(--radius-cv) -> "0px" while
// a defined control token on the same element -> "12px".

test("every radius token USED in index.css is DEFINED in it", () => {
  // Strip comments FIRST: a var() named inside prose (e.g. the `--code-token-<x>`
  // placeholder in the :root doc comment) is not a read at all, and matching it
  // makes this check fail on documentation.
  const live = CSS.replace(/\/\*[\s\S]*?\*\//g, "");
  const defined = new Set<string>();
  for (const m of live.matchAll(/(--[a-z0-9-]+)\s*:/g)) defined.add(m[1]!);
  // Tailwind's own namespace is generated by the framework, and the colour
  // channels carry --c-N aliases the theme engine owns; neither is this file's
  // job. Everything else that reads a var() must be able to resolve it.
  const generated = /^--(radius|duration|ease|spacing|text|leading|tracking|font-weight|breakpoint|container|shadow|blur|aspect)-/;
  // Supplied from OUTSIDE this stylesheet. `--pg-*`, `--pad-*`, `--x-gap` are
  // written by the A4 export as inline styles on the page box (canvas-export.tsx)
  // and every one of those reads carries its own CSS fallback (pinned below).
  // `--i` is React's internal style hook. `--cols` / `--cv-pct` /
  // `--astra-topbar-h` / `--color-signal` are set by the JS that lays out those
  // elements. None of them is a token this file forgot to declare.
  const external = /^--(pg-|pad-|x-gap$|cols$|cv-pct$|i$|astra-topbar-h$|color-signal$|layout-cols$)/;
  const missing = new Set<string>();
  for (const m of live.matchAll(/var\(\s*(--[a-z0-9-]+)/g)) {
    const name = m[1]!;
    if (defined.has(name) || generated.test(name) || external.test(name)) continue;
    missing.add(name);
  }
  assert.deepEqual(
    [...missing],
    [],
    `index.css reads custom properties it never defines: ${[...missing].join(", ")}`,
  );
});

test("an externally-supplied var has a CSS fallback where it is read", () => {
  // The exclusions above are only safe because each external read falls back.
  // Pin it: strip the fallback and the assertion below must find the offenders.
  const live = CSS.replace(/\/\*[\s\S]*?\*\//g, "");
  for (const name of ["--pg-w", "--pg-h", "--pad-x", "--pad-y", "--x-gap", "--layout-cols"]) {
    const re = new RegExp("var\\(\\s*" + name + "([^)]*)\\)", "g");
    for (const m of live.matchAll(re)) {
      assert.match(m[1]!, /,/, "var(" + name + ") needs a fallback, or the box collapses when unset");
    }
  }
});

test("the canvas geometry tokens exist and are real lengths", () => {
  for (const name of ["--radius-cv", "--radius-cv-soft"]) {
    const m = new RegExp(`${name}\\s*:\\s*([^;]+);`).exec(CSS);
    assert.ok(m, `${name} must be defined in :root`);
    assert.match(m[1]!.trim(), /^\d+(\.\d+)?(px|rem)$/, `${name} is a length, got ${m[1]}`);
  }
});

test("calc(var(--radius-cv) - Npx) is now a valid expression, not IACVT", () => {
  // The subtraction form is the one that silently collapsed to 0px before.
  const used = CSS.match(/calc\(\s*var\(--radius-cv\)\s*-\s*(\d+)px\s*\)/g) ?? [];
  assert.ok(used.length > 0, "the calc form should still be in use (pin the shape)");
  const cv = Number(/--radius-cv\s*:\s*([\d.]+)/.exec(CSS)?.[1]);
  for (const expr of used) {
    const sub = Number(/(\d+)px\s*\)/.exec(expr)?.[1]);
    assert.ok(cv - sub > 0, `calc(${expr}) must stay positive; --radius-cv is ${cv}px`);
  }
});

// ---- 2. the `page` envelope key ------------------------------------------
//
// The A4 / 16:9 rule is only meaningful if the key an author writes survives
// both the parser AND the sanitizer. Before this, `page` was dropped by
// parseCanvasSpec and then again by sanitizeCanvasSpec, so a rule naming it
// would have been decoration.

test("page survives the parser for every valid format", () => {
  for (const f of ["a4", "slide", "auto"]) {
    const spec = parseCanvasSpec(JSON.stringify({ v: 1, title: "t", page: f, blocks: BODY }));
    assert.ok(spec, `${f} must parse`);
    assert.equal(spec.page, f);
  }
});

test("the object spelling is accepted — dropping it is the bug this guards", () => {
  const spec = parseCanvasSpec(JSON.stringify({ v: 1, page: { format: "a4" }, blocks: BODY }));
  assert.equal(spec?.page, "a4");
});

test("an unknown page value is dropped, never coerced", () => {
  for (const bad of ["portrait", "A4", "letter", "16:9", "", 1, null, ["a4"]]) {
    const spec = parseCanvasSpec(JSON.stringify({ v: 1, page: bad, blocks: BODY }));
    assert.ok(spec, "the card itself must still parse");
    assert.equal(spec.page, undefined, `"${JSON.stringify(bad)}" must not become a format`);
  }
});

test("a card with no page key gains no page key", () => {
  // The pre-existing shape keeps `title: undefined` present, so this asserts
  // the ONE thing this change could break — that `page` is absent — rather
  // than deep-equality against a literal, which would fail on that long-
  // standing `title: undefined` and prove nothing about this edit.
  const spec = parseCanvasSpec(JSON.stringify({ v: 1, title: "t", blocks: BODY }));
  assert.ok(spec);
  assert.ok(!("page" in spec!), "the key must be absent, not undefined");
  assert.equal(spec.title, "t", "the surrounding envelope must be untouched");
  assert.equal(spec.blocks.length, 1);
});

test("page survives the sanitizer", () => {
  const spec = parseCanvasSpec(JSON.stringify({ v: 1, page: "a4", blocks: BODY }))!;
  const safe = sanitizeCanvasSpec(spec);
  assert.equal(safe?.page, "a4", "the render path must still know the format");
});

test("the sanitizer drops an invalid page rather than passing it through", () => {
  const safe = sanitizeCanvasSpec({ v: 1, page: "portrait" as never, blocks: BODY });
  assert.ok(safe);
  assert.equal(safe.page, undefined);
});

// ---- 3. the namespace contract the new engines depend on ------------------

test("applyPalette's Astra-UI reset preserves non-colour namespaces", () => {
  const src = readFileSync(resolve(__dirname, "./theme-store.ts"), "utf8");
  const decl = /FOREIGN_NAMESPACES\s*=\s*\[([^\]]+)\]/.exec(src);
  assert.ok(decl, "theme-store must declare FOREIGN_NAMESPACES");
  const ns = [...decl[1]!.matchAll(/"(--[a-z-]+)"/g)].map((m) => m[1]!);
  for (const want of ["--shape-", "--font-", "--brand-"]) {
    assert.ok(ns.includes(want), `${want} must be protected from the reset`);
  }
  // And the guard must actually be reached inside the isDefault branch, not
  // merely declared — a declared-but-unused constant reads as protection and
  // protects nothing.
  const branch = /if\s*\(isDefault\)\s*\{[\s\S]{0,500}?\n\s{4}return 0;/.exec(src);
  assert.ok(branch, "the reset branch must be locatable");
  const body = branch[0];
  assert.match(body, /FOREIGN_NAMESPACES/, "the branch must consult FOREIGN_NAMESPACES");
  // Colour channels must STILL be cleared: that is the branch's whole job.
  assert.match(body, /removeProperty/, "the branch must still remove colour props");
  // And the skip must be a `continue`, so a protected name cannot fall through
  // to the removal a line below it.
  assert.match(body, /continue;/, "a protected namespace must skip the removal, not fall through");
});
