// Canvas block downloads — write the bytes to disk SERVER-SIDE, then download
// by path. Never hand a blob: URL to an anchor.
//
// Why: anything a browser generates in memory (.xlsx/.docx/.pptx are all zips
// built in JS) reaches the download as blob:/data:, and the Android WebView
// refuses both outright (MainActivity.setDownloadListener → toast "Can't
// download this item"). That path works on web and silently fails on the APK,
// which is the surface a download matters most on.
//
// So: POST the data URL to /api/files/upload (upstream hermes_cli/web_routers/
// files.py), then hand the returned path to the existing downloadFile() helper,
// which builds /api/hx/files/download?path=… — an ordinary HTTP URL that
// Android DownloadManager handles like any other file.
//
// Never branch on Capacitor.isNativePlatform() here: that manufactures two
// behaviours and one of them is broken.
import { downloadFile } from "./download";

/** Where generated files land. Downloads dir first, then the session-ish home path. */
const DIRS = ["~/Downloads", "~"];

function base64ToDataUrl(bytes: Uint8Array, mime: string): string {
  let bin = "";
  const CH = 0x8000; // chunked so a large sheet never blows the argument limit
  for (let i = 0; i < bytes.length; i += CH) {
    bin += String.fromCharCode(...bytes.subarray(i, i + CH));
  }
  return `data:${mime};base64,${btoa(bin)}`;
}

/** Strip anything that could escape the target dir or upset a filesystem. */
function safeName(name: string): string {
  return (
    name
      .replace(/[\\/]+/g, "-")
      .replace(/\.{2,}/g, ".")
      .replace(/[^\w.\- ]+/g, "_")
      .replace(/^\.+/, "") || "canvas-export"
  );
}

export interface SaveResult {
  ok: boolean;
  path?: string;
  name: string;
  error?: string;
}

/**
 * Persist generated bytes to the host and hand back the canonical path.
 * Tries each candidate dir: the first that accepts wins, so a missing
 * ~/Downloads does not fail the download on an otherwise healthy host.
 */
export async function saveCanvasFile(
  bytes: Uint8Array,
  filename: string,
  mime: string,
): Promise<SaveResult> {
  const name = safeName(filename);
  const dataUrl = base64ToDataUrl(bytes, mime);
  let lastErr = "no directory available";
  for (const dir of DIRS) {
    for (let attempt = 0; attempt < 3; attempt++) {
      // Upload refuses to clobber an existing file without `overwrite`; a
      // name collision must never silently download yesterday's export.
      const stamped = attempt === 0 ? name : `${name.replace(/(\.[^.]+)?$/, `-${Date.now().toString(36)}$1`)}`;
      const path = `${dir}/${stamped}`;
      try {
        const res = await fetch("/api/hx/files/upload", {
          method: "POST",
          credentials: "same-origin",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ path, data_url: dataUrl, overwrite: true }),
        });
        if (!res.ok) {
          let detail = `HTTP ${res.status}`;
          try {
            const j = await res.json();
            if (j?.detail) detail = String(j.detail);
          } catch { /* body not json — keep the status */ }
          lastErr = detail;
          // A path rejection is not worth retrying on the same dir; the
          // next candidate dir may still be acceptable.
          if (res.status === 400 || res.status === 403) break;
          continue;
        }
        const j = await res.json();
        const real = typeof j?.path === "string" && j.path ? j.path : path;
        return { ok: true, path: real, name: stamped };
      } catch (e) {
        lastErr = String((e as Error)?.message ?? e);
        break; // network/transport failure — a retry hits the same wall
      }
    }
  }
  return { ok: false, name, error: lastErr };
}

/**
 * Generate → save to host → download by path. One call per Download button.
 * `produce` returns the bytes; it is only invoked once the pipeline is wired.
 */
export async function downloadCanvasFile(
  produce: () => Promise<Uint8Array> | Uint8Array,
  filename: string,
  mime: string,
): Promise<SaveResult> {
  try {
    const bytes = await produce();
    if (!bytes || bytes.length === 0) return { ok: false, name: filename, error: "nothing to export" };
    const saved = await saveCanvasFile(bytes, filename, mime);
    if (!saved.ok || !saved.path) return saved;
    downloadFile(saved.path, saved.name);
    return saved;
  } catch (e) {
    return { ok: false, name: filename, error: String((e as Error)?.message ?? e) };
  }
}